site_name: oneko 的小窝
site_url: https://qaqdev.github.io/
repo_name: QAQdev/something
repo_url: https://github.com/qaqdev/qaqdev.github.io
edit_uri: "tree/master/docs"
site_description: oneko 的小窝
copyright: Copyright &copy; 2023-2024 <a href="https://github.com/QAQdev" target="_blank" rel="noopener">oneko</a>

nav:
  - Home: index.md
  - About: about.md
theme:
  name: material
  language: 'zh'
  favicon: 'static/logo.ico'
  icon:
    logo: material/cat
    admonition:
      info: fontawesome/solid/circle-info
      note: fontawesome/solid/pen-nib
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: material/alien
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/link
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.follow # toc 跟随
  font:
    text: Lato
    code: Fira Code
  palette:
    primary: blue grey
    scheme: default

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
      # slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # enable Unicode link
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra:
  analytics:
    provider: google
    property: G-JT9BRCXKJJ

extra_css:
  - css/admontion.css

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - statistics

