site_name: oneko 的小窝
site_url: https://qaqdev.github.io/
repo_name: QAQdev/something
repo_url: https://github.com/qaqdev/qaqdev.github.io
edit_uri: ""
site_description: oneko 的小窝
copyright: Copyright &copy; 2023-2024 <a href="https://github.com/QAQdev" target="_blank" rel="noopener">oneko</a>

nav:
  - Home: index.md
  - About: about.md
theme:
  name: material
  language: 'zh'
  # favicon: 'logo.ico'
  icon:
    logo: material/cat
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.follow # toc 跟随
  font:
    text: Lato
    code: Fira Code
  palette:
    primary: blue grey
    scheme: default

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra:
  analytics:
    provider: google
    property: G-JT9BRCXKJJ

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - statistics:
      page_check_metadata: comment

