site_name: oneko verse
site_url: https://qaqdev.github.io/
repo_name: QAQdev/something
repo_url: https://github.com/qaqdev/qaqdev.github.io
edit_uri: "tree/master/docs"
site_description: oneko verse
copyright: Copyright &copy; 2023-2024 <a href="https://github.com/QAQdev" target="_blank" rel="noopener">oneko</a>

nav:
  - 主页: index.md
  - 关于: about.md

theme:
  name: material
  language: 'zh'
  favicon: 'static/logo.ico'
  icon:
    logo: material/cat
    admonition:
      info: fontawesome/solid/circle-info
      note: fontawesome/solid/pen-fancy
      abstract: fontawesome/solid/clipboard-list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/xmark
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/bug
      example: fontawesome/solid/flask
      quote: fontawesome/solid/link

  custom_dir: overrides

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow # toc 跟随
  font:
    text: Lato
    code: Fira Code
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      primary: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # enable Unicode link
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true

extra:
  analytics:
    provider: google
    property: G-XVCQ01HH08
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/QAQdev
      name: Github
    - icon: fontawesome/solid/dove
      link: https://www.yuque.com/oneko/something
    - icon: fontawesome/solid/paper-plane
      link: mailto:zhenglin.cheng.cc@gmail.com

extra_css:
  - css/admonition.css

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - statistics